import type { CircuitComponent, ComponentType, ComponentDefinition } from '../types';

export const COMPONENT_DEFINITIONS: Record<ComponentType, ComponentDefinition> = {
  resistor: {
    type: 'resistor',
    name: 'Resistor',
    category: 'passive',
    defaultValue: 10000,
    defaultUnit: 'Ω',
    pins: [
      { name: 'A', relativePosition: { x: 0, y: 20 } },
      { name: 'B', relativePosition: { x: 60, y: 20 } },
    ],
    width: 60,
    height: 40,
    symbol: 'resistor',
  },
  capacitor: {
    type: 'capacitor',
    name: 'Capacitor',
    category: 'passive',
    defaultValue: 0.1,
    defaultUnit: 'µF',
    pins: [
      { name: '+', relativePosition: { x: 0, y: 20 } },
      { name: '-', relativePosition: { x: 60, y: 20 } },
    ],
    width: 60,
    height: 40,
    symbol: 'capacitor',
  },
  inductor: {
    type: 'inductor',
    name: 'Inductor',
    category: 'passive',
    defaultValue: 10,
    defaultUnit: 'mH',
    pins: [
      { name: 'A', relativePosition: { x: 0, y: 20 } },
      { name: 'B', relativePosition: { x: 60, y: 20 } },
    ],
    width: 60,
    height: 40,
    symbol: 'inductor',
  },
  diode: {
    type: 'diode',
    name: 'Diode',
    category: 'semiconductor',
    defaultValue: '1N4148',
    defaultUnit: '',
    pins: [
      { name: 'A', relativePosition: { x: 0, y: 20 } },
      { name: 'K', relativePosition: { x: 60, y: 20 } },
    ],
    width: 60,
    height: 40,
    symbol: 'diode',
  },
  led: {
    type: 'led',
    name: 'LED',
    category: 'semiconductor',
    defaultValue: 'Red',
    defaultUnit: '',
    pins: [
      { name: 'A', relativePosition: { x: 0, y: 20 } },
      { name: 'K', relativePosition: { x: 60, y: 20 } },
    ],
    width: 60,
    height: 40,
    symbol: 'led',
  },
  zener: {
    type: 'zener',
    name: 'Zener Diode',
    category: 'semiconductor',
    defaultValue: 5.1,
    defaultUnit: 'V',
    pins: [
      { name: 'A', relativePosition: { x: 0, y: 20 } },
      { name: 'K', relativePosition: { x: 60, y: 20 } },
    ],
    width: 60,
    height: 40,
    symbol: 'zener',
  },
  transistor_npn: {
    type: 'transistor_npn',
    name: 'NPN Transistor',
    category: 'semiconductor',
    defaultValue: '2N3904',
    defaultUnit: '',
    pins: [
      { name: 'B', relativePosition: { x: 0, y: 30 } },
      { name: 'C', relativePosition: { x: 40, y: 0 } },
      { name: 'E', relativePosition: { x: 40, y: 60 } },
    ],
    width: 60,
    height: 60,
    symbol: 'transistor_npn',
  },
  transistor_pnp: {
    type: 'transistor_pnp',
    name: 'PNP Transistor',
    category: 'semiconductor',
    defaultValue: '2N3906',
    defaultUnit: '',
    pins: [
      { name: 'B', relativePosition: { x: 0, y: 30 } },
      { name: 'C', relativePosition: { x: 40, y: 60 } },
      { name: 'E', relativePosition: { x: 40, y: 0 } },
    ],
    width: 60,
    height: 60,
    symbol: 'transistor_pnp',
  },
  opamp: {
    type: 'opamp',
    name: 'Op-Amp',
    category: 'active',
    defaultValue: 'TL072',
    defaultUnit: '',
    pins: [
      { name: '+', relativePosition: { x: 0, y: 20 } },
      { name: '-', relativePosition: { x: 0, y: 60 } },
      { name: 'OUT', relativePosition: { x: 80, y: 40 } },
      { name: 'V+', relativePosition: { x: 40, y: 0 } },
      { name: 'V-', relativePosition: { x: 40, y: 80 } },
    ],
    width: 80,
    height: 80,
    symbol: 'opamp',
  },
  potentiometer: {
    type: 'potentiometer',
    name: 'Potentiometer',
    category: 'passive',
    defaultValue: 100000,
    defaultUnit: 'Ω',
    pins: [
      { name: '1', relativePosition: { x: 0, y: 20 } },
      { name: '2', relativePosition: { x: 30, y: 0 } },
      { name: '3', relativePosition: { x: 60, y: 20 } },
    ],
    width: 60,
    height: 50,
    symbol: 'potentiometer',
  },
  switch: {
    type: 'switch',
    name: 'Switch',
    category: 'passive',
    defaultValue: 'SPST',
    defaultUnit: '',
    pins: [
      { name: 'A', relativePosition: { x: 0, y: 20 } },
      { name: 'B', relativePosition: { x: 60, y: 20 } },
    ],
    width: 60,
    height: 40,
    symbol: 'switch',
  },
  input_jack: {
    type: 'input_jack',
    name: 'Input Jack',
    category: 'io',
    defaultValue: '1/4"',
    defaultUnit: '',
    pins: [
      { name: 'TIP', relativePosition: { x: 50, y: 15 } },
      { name: 'GND', relativePosition: { x: 50, y: 35 } },
    ],
    width: 50,
    height: 50,
    symbol: 'input_jack',
  },
  output_jack: {
    type: 'output_jack',
    name: 'Output Jack',
    category: 'io',
    defaultValue: '1/4"',
    defaultUnit: '',
    pins: [
      { name: 'TIP', relativePosition: { x: 0, y: 15 } },
      { name: 'GND', relativePosition: { x: 0, y: 35 } },
    ],
    width: 50,
    height: 50,
    symbol: 'output_jack',
  },
  ground: {
    type: 'ground',
    name: 'Ground',
    category: 'power',
    defaultValue: 0,
    defaultUnit: 'V',
    pins: [{ name: 'GND', relativePosition: { x: 20, y: 0 } }],
    width: 40,
    height: 30,
    symbol: 'ground',
  },
  vcc: {
    type: 'vcc',
    name: 'VCC',
    category: 'power',
    defaultValue: 9,
    defaultUnit: 'V',
    pins: [{ name: 'VCC', relativePosition: { x: 20, y: 30 } }],
    width: 40,
    height: 30,
    symbol: 'vcc',
  },
  oscillator: {
    type: 'oscillator',
    name: 'Oscillator',
    category: 'active',
    defaultValue: 440,
    defaultUnit: 'Hz',
    pins: [
      { name: 'OUT', relativePosition: { x: 60, y: 30 } },
      { name: 'CV', relativePosition: { x: 0, y: 30 } },
    ],
    width: 60,
    height: 60,
    symbol: 'oscillator',
  },
  speaker: {
    type: 'speaker',
    name: 'Speaker',
    category: 'io',
    defaultValue: 8,
    defaultUnit: 'Ω',
    pins: [
      { name: '+', relativePosition: { x: 0, y: 25 } },
      { name: '-', relativePosition: { x: 0, y: 45 } },
    ],
    width: 50,
    height: 70,
    symbol: 'speaker',
  },
  mosfet_n: {
    type: 'mosfet_n',
    name: 'N-MOSFET',
    category: 'semiconductor',
    defaultValue: '2N7000',
    defaultUnit: '',
    pins: [
      { name: 'G', relativePosition: { x: 0, y: 30 } },
      { name: 'D', relativePosition: { x: 40, y: 0 } },
      { name: 'S', relativePosition: { x: 40, y: 60 } },
    ],
    width: 60,
    height: 60,
    symbol: 'mosfet_n',
  },
  mosfet_p: {
    type: 'mosfet_p',
    name: 'P-MOSFET',
    category: 'semiconductor',
    defaultValue: 'BS250',
    defaultUnit: '',
    pins: [
      { name: 'G', relativePosition: { x: 0, y: 30 } },
      { name: 'D', relativePosition: { x: 40, y: 60 } },
      { name: 'S', relativePosition: { x: 40, y: 0 } },
    ],
    width: 60,
    height: 60,
    symbol: 'mosfet_p',
  },
  jfet_n: {
    type: 'jfet_n',
    name: 'N-JFET',
    category: 'semiconductor',
    defaultValue: 'J201',
    defaultUnit: '',
    pins: [
      { name: 'G', relativePosition: { x: 0, y: 30 } },
      { name: 'D', relativePosition: { x: 40, y: 0 } },
      { name: 'S', relativePosition: { x: 40, y: 60 } },
    ],
    width: 60,
    height: 60,
    symbol: 'jfet_n',
  },
  jfet_p: {
    type: 'jfet_p',
    name: 'P-JFET',
    category: 'semiconductor',
    defaultValue: 'J175',
    defaultUnit: '',
    pins: [
      { name: 'G', relativePosition: { x: 0, y: 30 } },
      { name: 'D', relativePosition: { x: 40, y: 60 } },
      { name: 'S', relativePosition: { x: 40, y: 0 } },
    ],
    width: 60,
    height: 60,
    symbol: 'jfet_p',
  },
  timer_555: {
    type: 'timer_555',
    name: '555 Timer',
    category: 'active',
    defaultValue: 'NE555',
    defaultUnit: '',
    pins: [
      { name: 'GND', relativePosition: { x: 0, y: 70 } },
      { name: 'TRIG', relativePosition: { x: 0, y: 50 } },
      { name: 'OUT', relativePosition: { x: 80, y: 30 } },
      { name: 'RESET', relativePosition: { x: 0, y: 10 } },
      { name: 'CTRL', relativePosition: { x: 80, y: 50 } },
      { name: 'THRES', relativePosition: { x: 0, y: 30 } },
      { name: 'DISCH', relativePosition: { x: 80, y: 10 } },
      { name: 'VCC', relativePosition: { x: 80, y: 70 } },
    ],
    width: 80,
    height: 80,
    symbol: 'timer_555',
  },
  cd40106: {
    type: 'cd40106',
    name: 'CD40106 Schmitt',
    category: 'active',
    defaultValue: 'CD40106',
    defaultUnit: '',
    pins: [
      { name: '1A', relativePosition: { x: 0, y: 10 } },
      { name: '1Y', relativePosition: { x: 0, y: 25 } },
      { name: '2A', relativePosition: { x: 0, y: 40 } },
      { name: '2Y', relativePosition: { x: 0, y: 55 } },
      { name: '3A', relativePosition: { x: 0, y: 70 } },
      { name: '3Y', relativePosition: { x: 0, y: 85 } },
      { name: 'GND', relativePosition: { x: 40, y: 95 } },
      { name: '4A', relativePosition: { x: 80, y: 85 } },
      { name: '4Y', relativePosition: { x: 80, y: 70 } },
      { name: '5A', relativePosition: { x: 80, y: 55 } },
      { name: '5Y', relativePosition: { x: 80, y: 40 } },
      { name: '6A', relativePosition: { x: 80, y: 25 } },
      { name: '6Y', relativePosition: { x: 80, y: 10 } },
      { name: 'VCC', relativePosition: { x: 40, y: 0 } },
    ],
    width: 80,
    height: 100,
    symbol: 'cd40106',
  },
  cd4017: {
    type: 'cd4017',
    name: 'CD4017 Decade',
    category: 'active',
    defaultValue: 'CD4017',
    defaultUnit: '',
    pins: [
      { name: 'Q5', relativePosition: { x: 0, y: 10 } },
      { name: 'Q1', relativePosition: { x: 0, y: 25 } },
      { name: 'Q0', relativePosition: { x: 0, y: 40 } },
      { name: 'Q2', relativePosition: { x: 0, y: 55 } },
      { name: 'Q6', relativePosition: { x: 0, y: 70 } },
      { name: 'Q7', relativePosition: { x: 0, y: 85 } },
      { name: 'Q3', relativePosition: { x: 0, y: 100 } },
      { name: 'GND', relativePosition: { x: 0, y: 115 } },
      { name: 'Q8', relativePosition: { x: 80, y: 115 } },
      { name: 'Q4', relativePosition: { x: 80, y: 100 } },
      { name: 'Q9', relativePosition: { x: 80, y: 85 } },
      { name: 'CO', relativePosition: { x: 80, y: 70 } },
      { name: 'CLK', relativePosition: { x: 80, y: 55 } },
      { name: 'INH', relativePosition: { x: 80, y: 40 } },
      { name: 'RST', relativePosition: { x: 80, y: 25 } },
      { name: 'VCC', relativePosition: { x: 80, y: 10 } },
    ],
    width: 80,
    height: 130,
    symbol: 'cd4017',
  },
  cd4040: {
    type: 'cd4040',
    name: 'CD4040 Counter',
    category: 'active',
    defaultValue: 'CD4040',
    defaultUnit: '',
    pins: [
      { name: 'Q12', relativePosition: { x: 0, y: 10 } },
      { name: 'Q6', relativePosition: { x: 0, y: 25 } },
      { name: 'Q5', relativePosition: { x: 0, y: 40 } },
      { name: 'Q7', relativePosition: { x: 0, y: 55 } },
      { name: 'Q4', relativePosition: { x: 0, y: 70 } },
      { name: 'Q3', relativePosition: { x: 0, y: 85 } },
      { name: 'Q2', relativePosition: { x: 0, y: 100 } },
      { name: 'GND', relativePosition: { x: 0, y: 115 } },
      { name: 'Q1', relativePosition: { x: 80, y: 115 } },
      { name: 'CLK', relativePosition: { x: 80, y: 100 } },
      { name: 'RST', relativePosition: { x: 80, y: 85 } },
      { name: 'Q9', relativePosition: { x: 80, y: 70 } },
      { name: 'Q8', relativePosition: { x: 80, y: 55 } },
      { name: 'Q10', relativePosition: { x: 80, y: 40 } },
      { name: 'Q11', relativePosition: { x: 80, y: 25 } },
      { name: 'VCC', relativePosition: { x: 80, y: 10 } },
    ],
    width: 80,
    height: 130,
    symbol: 'cd4040',
  },
  cd4049: {
    type: 'cd4049',
    name: 'CD4049 Inverter',
    category: 'active',
    defaultValue: 'CD4049',
    defaultUnit: '',
    pins: [
      { name: 'VCC', relativePosition: { x: 0, y: 10 } },
      { name: '1Y', relativePosition: { x: 0, y: 25 } },
      { name: '1A', relativePosition: { x: 0, y: 40 } },
      { name: '2Y', relativePosition: { x: 0, y: 55 } },
      { name: '2A', relativePosition: { x: 0, y: 70 } },
      { name: '3Y', relativePosition: { x: 0, y: 85 } },
      { name: '3A', relativePosition: { x: 0, y: 100 } },
      { name: 'GND', relativePosition: { x: 0, y: 115 } },
      { name: '4A', relativePosition: { x: 80, y: 115 } },
      { name: '4Y', relativePosition: { x: 80, y: 100 } },
      { name: '5A', relativePosition: { x: 80, y: 85 } },
      { name: '5Y', relativePosition: { x: 80, y: 70 } },
      { name: '6A', relativePosition: { x: 80, y: 55 } },
      { name: '6Y', relativePosition: { x: 80, y: 40 } },
      { name: 'NC', relativePosition: { x: 80, y: 25 } },
      { name: 'NC2', relativePosition: { x: 80, y: 10 } },
    ],
    width: 80,
    height: 130,
    symbol: 'cd4049',
  },
  cd4066: {
    type: 'cd4066',
    name: 'CD4066 Switch',
    category: 'active',
    defaultValue: 'CD4066',
    defaultUnit: '',
    pins: [
      { name: '1IO', relativePosition: { x: 0, y: 10 } },
      { name: '1O', relativePosition: { x: 0, y: 25 } },
      { name: '2O', relativePosition: { x: 0, y: 40 } },
      { name: '2IO', relativePosition: { x: 0, y: 55 } },
      { name: '2C', relativePosition: { x: 0, y: 70 } },
      { name: '3C', relativePosition: { x: 0, y: 85 } },
      { name: 'GND', relativePosition: { x: 0, y: 100 } },
      { name: 'VCC', relativePosition: { x: 80, y: 100 } },
      { name: '4C', relativePosition: { x: 80, y: 85 } },
      { name: '4IO', relativePosition: { x: 80, y: 70 } },
      { name: '4O', relativePosition: { x: 80, y: 55 } },
      { name: '3O', relativePosition: { x: 80, y: 40 } },
      { name: '3IO', relativePosition: { x: 80, y: 25 } },
      { name: '1C', relativePosition: { x: 80, y: 10 } },
    ],
    width: 80,
    height: 115,
    symbol: 'cd4066',
  },
  pt2399: {
    type: 'pt2399',
    name: 'PT2399 Delay',
    category: 'active',
    defaultValue: 'PT2399',
    defaultUnit: '',
    pins: [
      { name: 'SDOUT', relativePosition: { x: 0, y: 10 } },
      { name: 'VCO2', relativePosition: { x: 0, y: 25 } },
      { name: 'VCO1', relativePosition: { x: 0, y: 40 } },
      { name: 'RIN', relativePosition: { x: 0, y: 55 } },
      { name: 'LIN', relativePosition: { x: 0, y: 70 } },
      { name: 'OPND', relativePosition: { x: 0, y: 85 } },
      { name: 'OP-', relativePosition: { x: 0, y: 100 } },
      { name: 'GND', relativePosition: { x: 0, y: 115 } },
      { name: 'VCC', relativePosition: { x: 80, y: 115 } },
      { name: 'OP+', relativePosition: { x: 80, y: 100 } },
      { name: 'REF', relativePosition: { x: 80, y: 85 } },
      { name: 'NC', relativePosition: { x: 80, y: 70 } },
      { name: 'AI', relativePosition: { x: 80, y: 55 } },
      { name: 'AO', relativePosition: { x: 80, y: 40 } },
      { name: 'SDIN', relativePosition: { x: 80, y: 25 } },
      { name: 'TEST', relativePosition: { x: 80, y: 10 } },
    ],
    width: 80,
    height: 130,
    symbol: 'pt2399',
  },
  optocoupler: {
    type: 'optocoupler',
    name: 'Optocoupler',
    category: 'semiconductor',
    defaultValue: 'VTL5C',
    defaultUnit: '',
    pins: [
      { name: 'LED+', relativePosition: { x: 0, y: 15 } },
      { name: 'LED-', relativePosition: { x: 0, y: 45 } },
      { name: 'LDR1', relativePosition: { x: 60, y: 15 } },
      { name: 'LDR2', relativePosition: { x: 60, y: 45 } },
    ],
    width: 60,
    height: 60,
    symbol: 'optocoupler',
  },
  ldr: {
    type: 'ldr',
    name: 'LDR/Photoresistor',
    category: 'passive',
    defaultValue: 10000,
    defaultUnit: 'Ω',
    pins: [
      { name: 'A', relativePosition: { x: 0, y: 20 } },
      { name: 'B', relativePosition: { x: 60, y: 20 } },
    ],
    width: 60,
    height: 40,
    symbol: 'ldr',
  },
  regulator: {
    type: 'regulator',
    name: 'Voltage Regulator',
    category: 'power',
    defaultValue: '7809',
    defaultUnit: '',
    pins: [
      { name: 'IN', relativePosition: { x: 0, y: 25 } },
      { name: 'GND', relativePosition: { x: 30, y: 50 } },
      { name: 'OUT', relativePosition: { x: 60, y: 25 } },
    ],
    width: 60,
    height: 50,
    symbol: 'regulator',
  },
};

export function createComponent(
  type: ComponentType,
  position: { x: number; y: number }
): CircuitComponent {
  const definition = COMPONENT_DEFINITIONS[type];

  return {
    id: `${type}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    type,
    position,
    rotation: 0,
    value: definition.defaultValue,
    unit: definition.defaultUnit,
    pins: definition.pins.map((pinDef, index) => ({
      id: `pin-${index}`,
      name: pinDef.name,
      position: pinDef.relativePosition,
      connected: false,
    })),
    selected: false,
  };
}

export function getComponentDefinition(type: ComponentType): ComponentDefinition {
  return COMPONENT_DEFINITIONS[type];
}

export function formatValue(value: number | string, unit: string): string {
  if (typeof value === 'string') return value;

  if (unit === 'Ω' || unit === 'F' || unit === 'H') {
    if (value >= 1000000) return `${(value / 1000000).toFixed(1)}M${unit}`;
    if (value >= 1000) return `${(value / 1000).toFixed(1)}k${unit}`;
    if (value < 0.001) return `${(value * 1000000).toFixed(1)}µ${unit}`;
    if (value < 1) return `${(value * 1000).toFixed(1)}m${unit}`;
  }

  return `${value}${unit}`;
}
